repos:
-   repo: https://github.com/GitGuardian/ggshield
    rev: v1.21.0
    hooks:
    -   id: ggshield

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      -   id: remove-crlf
